using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Windows.Forms;

namespace GdipuDesktop
{
    internal sealed partial class MainForm
    {
        static string X(string value){if(value==null)return "";return value.Replace("&","&amp;").Replace("<","&lt;").Replace(">","&gt;").Replace("\"","&quot;").Replace("'","&apos;");}
        static void Entry(ZipArchive zip,string name,string content){var entry=zip.CreateEntry(name,CompressionLevel.Optimal);using(var writer=new StreamWriter(entry.Open(),new UTF8Encoding(false)))writer.Write(content);}
        DateTime? FirstDate(string value){var m=System.Text.RegularExpressions.Regex.Match(value??"",@"(\d{4})[/-](\d{1,2})[/-](\d{1,2})\s+(\d{1,2}):(\d{2})");DateTime d;if(!m.Success||!DateTime.TryParse(m.Groups[1].Value+"-"+m.Groups[2].Value+"-"+m.Groups[3].Value+" "+m.Groups[4].Value+":"+m.Groups[5].Value,out d))return null;return d;}
        DateTime? LastDate(string value){var ms=System.Text.RegularExpressions.Regex.Matches(value??"",@"(\d{4})[/-](\d{1,2})[/-](\d{1,2})\s+(\d{1,2}):(\d{2})");if(ms.Count<2)return null;var m=ms[1];DateTime d;if(!DateTime.TryParse(m.Groups[1].Value+"-"+m.Groups[2].Value+"-"+m.Groups[3].Value+" "+m.Groups[4].Value+":"+m.Groups[5].Value,out d))return null;return d;}
        string ExcelStatus(Dictionary<string,object> row,DateTime now){DateTime? start=FirstDate(Str(row,"registration")),end=LastDate(Str(row,"registration"));if(!start.HasValue||!end.HasValue)return "时间待确认";if(now<start.Value)return "报名未开始";if(now>=end.Value)return "报名已截止";if(Str(row,"remaining")=="0")return "名额已满";return "报名时间内";}
        string Cell(string address,string value,int style){return "<c r=\""+address+"\" s=\""+style+"\" t=\"inlineStr\"><is><t xml:space=\"preserve\">"+X(value)+"</t></is></c>";}
        string NumberCell(string address,double value,int style){return "<c r=\""+address+"\" s=\""+style+"\"><v>"+value.ToString(System.Globalization.CultureInfo.InvariantCulture)+"</v></c>";}
        string DateCell(string address,DateTime? value,int style){return value.HasValue?NumberCell(address,value.Value.ToOADate(),style):Cell(address,"",5);}
        string ValueCell(string address,string value,int style){int n;return int.TryParse(value,out n)?NumberCell(address,n,6):Cell(address,value,style);}
        void ExportExcel(List<Dictionary<string,object>> selected)
        {
            var ordered=selected.Where(r=>!IgnoredActivity(r)).OrderBy(r=>FirstDate(Str(r,"registration"))??DateTime.MaxValue).ThenBy(r=>Str(r,"name"),StringComparer.CurrentCulture).ToList();
            string target;if(testing){target=Path.Combine(dataDir,"未开始活动_测试.xlsx");testXlsx=target;}else{using(var dialog=new SaveFileDialog{FileName="未开始活动_"+DateTime.Now.ToString("yyyy-MM-dd")+".xlsx",Filter="Excel 工作簿 (*.xlsx)|*.xlsx",OverwritePrompt=true}){if(dialog.ShowDialog(this)!=DialogResult.OK)return;target=dialog.FileName;}}
            string temp=target+".tmp";if(File.Exists(temp))File.Delete(temp);using(var file=File.Create(temp))using(var zip=new ZipArchive(file,ZipArchiveMode.Create,true))WriteExcel(zip,ordered);if(File.Exists(target))File.Replace(temp,target,null);else File.Move(temp,target);if(!testing)statusLabel.Text="已导出 Excel："+target;
        }
        void WriteExcel(ZipArchive zip,List<Dictionary<string,object>> data)
        {
            int last=4+Math.Max(data.Count,1);string range="A4:K"+last;
            Entry(zip,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/><Override PartName=\"/xl/tables/table1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml\"/><Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/><Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/></Types>");
            Entry(zip,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/><Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/></Relationships>");
            Entry(zip,"docProps/core.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><dc:title>未开始活动汇总</dc:title><dc:creator>广轻活动汇总</dc:creator><dcterms:created xsi:type=\"dcterms:W3CDTF\">"+DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ")+"</dcterms:created></cp:coreProperties>");
            Entry(zip,"docProps/app.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\"><Application>广轻活动汇总</Application></Properties>");
            Entry(zip,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"活动汇总\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");
            Entry(zip,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>");
            Entry(zip,"xl/styles.xml",StylesXml());
            var s=new StringBuilder();s.Append("<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheetViews><sheetView workbookViewId=\"0\" showGridLines=\"0\"><pane ySplit=\"4\" topLeftCell=\"A5\" activePane=\"bottomLeft\" state=\"frozen\"/></sheetView></sheetViews><cols>");double[] widths={34,14,30,19,19,30,27,11,11,11,14};for(int i=0;i<widths.Length;i++)s.Append("<col min=\""+(i+1)+"\" max=\""+(i+1)+"\" width=\""+widths[i]+"\" customWidth=\"1\"/>");s.Append("</cols><sheetData>");
            s.Append("<row r=\"1\" ht=\"30\" customHeight=\"1\">").Append(Cell("A1","未开始活动汇总",1)).Append("</row><row r=\"2\" ht=\"22\" customHeight=\"1\">").Append(Cell("A2","按报名开始时间升序 · 已排除团日、班会和班级活动 · 共 "+data.Count+" 项",2)).Append("</row><row r=\"3\" ht=\"8\" customHeight=\"1\"/>");
            string[] headers={"活动名称","活动类型","发起组织","报名开始","报名截止","活动地点","活动时间","总名额","剩余名额","已报名","报名状态"};s.Append("<row r=\"4\" ht=\"28\" customHeight=\"1\">");for(int i=0;i<headers.Length;i++)s.Append(Cell(((char)('A'+i))+"4",headers[i],3));s.Append("</row>");DateTime now=DateTime.UtcNow.AddHours(8);
            for(int i=0;i<data.Count;i++){int r=5+i;var row=data[i];s.Append("<row r=\""+r+"\" ht=\"42\" customHeight=\"1\">");s.Append(Cell("A"+r,Str(row,"name"),5));s.Append(Cell("B"+r,Str(row,"type"),5));s.Append(Cell("C"+r,Str(row,"organizer"),5));s.Append(DateCell("D"+r,FirstDate(Str(row,"registration")),4));s.Append(DateCell("E"+r,LastDate(Str(row,"registration")),4));s.Append(Cell("F"+r,Str(row,"place"),5));s.Append(Cell("G"+r,Str(row,"activityTime"),5));s.Append(ValueCell("H"+r,Str(row,"capacity"),6));s.Append(ValueCell("I"+r,Str(row,"remaining"),6));s.Append(ValueCell("J"+r,Str(row,"registered"),6));s.Append(Cell("K"+r,ExcelStatus(row,now),5));s.Append("</row>");}
            if(data.Count==0)s.Append("<row r=\"5\"><c r=\"A5\" t=\"inlineStr\"><is><t>暂无符合条件的活动</t></is></c></row>");s.Append("</sheetData><mergeCells count=\"2\"><mergeCell ref=\"A1:K1\"/><mergeCell ref=\"A2:K2\"/></mergeCells><autoFilter ref=\""+range+"\"/><tableParts count=\"1\"><tablePart r:id=\"rId1\"/></tableParts></worksheet>");Entry(zip,"xl/worksheets/sheet1.xml",s.ToString());
            Entry(zip,"xl/worksheets/_rels/sheet1.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/table\" Target=\"../tables/table1.xml\"/></Relationships>");
            var t=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><table xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" id=\"1\" name=\"ActivitiesTable\" displayName=\"ActivitiesTable\" ref=\"").Append(range).Append("\" totalsRowShown=\"0\"><autoFilter ref=\"").Append(range).Append("\"/><tableColumns count=\"11\">");for(int i=0;i<headers.Length;i++)t.Append("<tableColumn id=\""+(i+1)+"\" name=\""+X(headers[i])+"\"/>");t.Append("</tableColumns><tableStyleInfo name=\"TableStyleMedium2\" showFirstColumn=\"0\" showLastColumn=\"0\" showRowStripes=\"1\" showColumnStripes=\"0\"/></table>");Entry(zip,"xl/tables/table1.xml",t.ToString());
        }
        string StylesXml(){return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><numFmts count=\"1\"><numFmt numFmtId=\"164\" formatCode=\"yyyy-mm-dd hh:mm\"/></numFmts><fonts count=\"4\"><font><sz val=\"10\"/><name val=\"Microsoft YaHei\"/><color rgb=\"FF243C4B\"/></font><font><b/><sz val=\"16\"/><name val=\"Microsoft YaHei\"/><color rgb=\"FF173746\"/></font><font><i/><sz val=\"10\"/><name val=\"Microsoft YaHei\"/><color rgb=\"FF607985\"/></font><font><b/><sz val=\"10\"/><name val=\"Microsoft YaHei\"/><color rgb=\"FFFFFFFF\"/></font></fonts><fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FF087D75\"/><bgColor indexed=\"64\"/></patternFill></fill></fills><borders count=\"2\"><border><left/><right/><top/><bottom/><diagonal/></border><border><left/><right/><top/><bottom style=\"thin\"><color rgb=\"FFDDE8EC\"/></bottom><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"7\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"2\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyAlignment=\"1\"><alignment vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"3\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\" applyNumberFormat=\"1\" applyAlignment=\"1\"><alignment horizontal=\"center\" vertical=\"center\"/></xf><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\" applyAlignment=\"1\"><alignment vertical=\"center\" wrapText=\"1\"/></xf><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"1\" xfId=\"0\" applyAlignment=\"1\"><alignment horizontal=\"right\" vertical=\"center\"/></xf></cellXfs><cellStyles count=\"1\"><cellStyle name=\"Normal\" xfId=\"0\" builtinId=\"0\"/></cellStyles></styleSheet>";}
        bool VerifyExcel(string path,int expected){try{using(var zip=ZipFile.OpenRead(path)){ZipArchiveEntry sheet=zip.GetEntry("xl/worksheets/sheet1.xml"),table=zip.GetEntry("xl/tables/table1.xml"),styles=zip.GetEntry("xl/styles.xml");if(sheet==null||table==null||styles==null)return false;using(var reader=new StreamReader(sheet.Open(),Encoding.UTF8)){string xml=reader.ReadToEnd();return xml.Contains("ySplit=\"4\"")&&xml.Contains("tableParts")&&System.Text.RegularExpressions.Regex.Matches(xml,"<row r=\"").Count==expected+4;}}}catch{return false;}}
    }
}
